### ISSUE TITLE
Error when running frida

### ISSUE THREAD

**Issue by Jelen0126** [Loli-Killer/ArknightsBattleSimulator#2]
This error popped up when I was running frida
/system/bin/sh: ./frida-server: not executable: magic 4D5A

**Comment by Loli-Killer** [comment]
Did you forgot the decompress the .xz file first?
https://github.com/frida/frida/issues/538

**Comment by Jelen0126** [comment]
No, I've unpacked the xz file

**Comment by Jelen0126** [comment]
I also tried not to unzip the xz file, but it all ended in failure

**Comment by Loli-Killer** [comment]
What device are you trying this on? 
So far, I've only tested it on mumu player 64-bit, and someone else said it worked in ldplayer 9 64-bit.

**Comment by Jelen0126** [comment]
I tried it on Nox

**Comment by Loli-Killer** [comment]
Do you have a discord? It would be better and easier to communicate on that rather than using this. The link is in the readme.

**Comment by Jelen0126** [comment]
Sure, it's a good idea.

**Comment by Jelen0126** [comment]
What is your id in discord?
